name: Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:  # Optional: Add unit testing on pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Adjust OS if needed

    steps:
      - uses: actions/checkout@v3  # Latest version for potential improvements

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Replace with your required version

      - name: I. Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: II. Install dependencies
        run: |
          pip install -r requirements.txt

      - name: III. Run Unit Tests
        # Option 1: Execute specific test file
        run: |
          python dashboard_CLOUD_with_UNIT_TESTING.py
